### ISSUE TITLE
Suggestion to use a different folder than `/root` for caching

### ISSUE THREAD

**Issue by Stef16Robbe** [astral-sh/uv-docker-example#27]
Some containerized environments, such as OpenShift keep the root file system read-only by default (for good reasons).

I edited the Dockerfile on my end to use `/tmp/.cache/uv` instead (and also added `UV_CACHE_DIR=/tmp/.cache/uv` env var).

Curious if there was a specific reason for choosing `/root` and if you see any issues with using `/tmp` instead.

**Comment by zanieb** [comment]
I think we use `/root` because it matches the default cache location. Choosing an alternative directory seems fine.

**Comment by Stef16Robbe** [comment]
Clear. Thanks for all the awesome work!
